#ifdef __CLING__
#pragma cling optimize(0)
#endif
void MACRO_cRelYields_Error_YieldsTree_BBMULTGENERAL_beauty_LbSb()
{
//=========Macro generated from canvas: cRelYields_integrated yields for B^{+} trigger as function of multiplicity/cRelYields
//=========  (Thu Apr 18 16:08:39 2024) by ROOT version 6.28/04
   TCanvas *cRelYields_integrated yields for B^{+} trigger as function of multiplicity = new TCanvas("cRelYields_integrated yields for B^{+} trigger as function of multiplicity", "cRelYields",2080,154,800,600);
   cRelYields_integrated->Range(0,0,1,1);
   cRelYields_integrated->SetFillColor(0);
   cRelYields_integrated->SetBorderMode(0);
   cRelYields_integrated->SetBorderSize(2);
   cRelYields_integrated->SetLeftMargin(0.15);
   cRelYields_integrated->SetRightMargin(0.25);
   cRelYields_integrated->SetBottomMargin(0.25);
   cRelYields_integrated->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: mainPadRelJunctions_integrated yields for B^{+} trigger as function of multiplicity
   TPad *mainPadRelJunctions_integrated = new TPad("mainPadRelJunctions_integrated yields for B^{+} trigger as function of multiplicity", "mainPad",0.05,0.3,0.95,0.95);
   mainPadRelJunctions_integrated->Draw();
   mainPadRelJunctions_integrated->cd();
   mainPadRelJunctions_integrated->Range(-0.8750001,-2.69897,7.875,0.9688411);
   mainPadRelJunctions_integrated->SetFillColor(0);
   mainPadRelJunctions_integrated->SetBorderMode(0);
   mainPadRelJunctions_integrated->SetBorderSize(2);
   mainPadRelJunctions_integrated->SetLogy();
   mainPadRelJunctions_integrated->SetBottomMargin(0);
   mainPadRelJunctions_integrated->SetFrameBorderMode(0);
   mainPadRelJunctions_integrated->SetFrameBorderMode(0);
   
   TH1D *hRelYieldsTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__364 = new TH1D("hRelYieldsTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__364","integrated yields for B^{+} trigger as function of multiplicity",7,0,7);
   hRelYieldsTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__364->SetMinimum(0.002);
   hRelYieldsTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__364->SetMaximum(4);
   hRelYieldsTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__364->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   hRelYieldsTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__364->SetLineColor(ci);
   hRelYieldsTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__364->GetXaxis()->SetLabelFont(42);
   hRelYieldsTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__364->GetXaxis()->SetLabelSize(0.05);
   hRelYieldsTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__364->GetXaxis()->SetTitleOffset(1);
   hRelYieldsTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__364->GetXaxis()->SetTitleFont(42);
   hRelYieldsTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__364->GetYaxis()->SetTitle("baryon/meson yield");
   hRelYieldsTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__364->GetYaxis()->SetLabelFont(42);
   hRelYieldsTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__364->GetYaxis()->SetTitleFont(42);
   hRelYieldsTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__364->GetZaxis()->SetLabelFont(42);
   hRelYieldsTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__364->GetZaxis()->SetTitleOffset(1);
   hRelYieldsTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__364->GetZaxis()->SetTitleFont(42);
   hRelYieldsTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__364->Draw("PE");
   
   TLegend *leg = new TLegend(0.63,0.68,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetTextSize(0.03);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("NULL","MONASH","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("NULL","JUNCTIONS","l");

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hRelYields_MONASH_integrated yields for B^{+} trigger as function of multiplicity_56_0","B^{+}#Lambda_{b}^{0}/B^{+}B^{-}","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hRelYields_MONASH_integrated yields for B^{+} trigger as function of multiplicity_84_0","B^{+}#Sigma_{b}^{0}/B^{+}B^{-}","l");
   entry->SetLineColor(1);
   entry->SetLineStyle(2);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   TH1D *hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__365 = new TH1D("hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__365","hRelYields_56_0",7,0,7);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__365->SetBinContent(1,0.07596721);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__365->SetBinError(1,0.000302524);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__365->SetEntries(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__365->GetXaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__365->GetXaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__365->GetXaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__365->GetYaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__365->GetYaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__365->GetZaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__365->GetZaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__365->GetZaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__365->Draw("same PE");
   
   TH1D *hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__366 = new TH1D("hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__366","hRelYields_56_0",7,0,7);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__366->SetBinContent(1,0.1381588);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__366->SetBinError(1,0.001103693);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__366->SetEntries(1);

   ci = TColor::GetColor("#ff0000");
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__366->SetLineColor(ci);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__366->GetXaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__366->GetXaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__366->GetXaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__366->GetYaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__366->GetYaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__366->GetZaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__366->GetZaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__366->GetZaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__366->Draw("same PE");
   
   TH1D *hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__367 = new TH1D("hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__367","hRelYields_56_1",7,0,7);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__367->SetBinContent(2,0.07587484);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__367->SetBinError(2,0.0002815033);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__367->SetEntries(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__367->GetXaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__367->GetXaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__367->GetXaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__367->GetYaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__367->GetYaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__367->GetZaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__367->GetZaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__367->GetZaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__367->Draw("same PE");
   
   TH1D *hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__368 = new TH1D("hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__368","hRelYields_56_1",7,0,7);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__368->SetBinContent(2,0.230639);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__368->SetBinError(2,0.001290936);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__368->SetEntries(1);

   ci = TColor::GetColor("#ff0000");
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__368->SetLineColor(ci);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__368->GetXaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__368->GetXaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__368->GetXaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__368->GetYaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__368->GetYaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__368->GetZaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__368->GetZaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__368->GetZaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__368->Draw("same PE");
   
   TH1D *hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__369 = new TH1D("hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__369","hRelYields_56_2",7,0,7);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__369->SetBinContent(3,0.07721588);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__369->SetBinError(3,0.0005088646);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__369->SetEntries(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__369->GetXaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__369->GetXaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__369->GetXaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__369->GetYaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__369->GetYaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__369->GetZaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__369->GetZaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__369->GetZaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__369->Draw("same PE");
   
   TH1D *hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__370 = new TH1D("hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__370","hRelYields_56_2",7,0,7);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__370->SetBinContent(3,0.2897852);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__370->SetBinError(3,0.001820998);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__370->SetEntries(1);

   ci = TColor::GetColor("#ff0000");
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__370->SetLineColor(ci);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__370->GetXaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__370->GetXaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__370->GetXaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__370->GetYaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__370->GetYaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__370->GetZaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__370->GetZaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__370->GetZaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__370->Draw("same PE");
   
   TH1D *hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__371 = new TH1D("hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__371","hRelYields_56_3",7,0,7);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__371->SetBinContent(4,0.07883188);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__371->SetBinError(4,0.0002846872);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__371->SetEntries(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__371->GetXaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__371->GetXaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__371->GetXaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__371->GetYaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__371->GetYaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__371->GetZaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__371->GetZaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__371->GetZaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__371->Draw("same PE");
   
   TH1D *hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__372 = new TH1D("hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__372","hRelYields_56_3",7,0,7);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__372->SetBinContent(4,0.3353132);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__372->SetBinError(4,0.001969886);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__372->SetEntries(1);

   ci = TColor::GetColor("#ff0000");
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__372->SetLineColor(ci);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__372->GetXaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__372->GetXaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__372->GetXaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__372->GetYaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__372->GetYaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__372->GetZaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__372->GetZaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__372->GetZaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__372->Draw("same PE");
   
   TH1D *hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__373 = new TH1D("hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__373","hRelYields_56_4",7,0,7);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__373->SetBinContent(5,0.07994347);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__373->SetBinError(5,0.0004823898);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__373->SetEntries(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__373->GetXaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__373->GetXaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__373->GetXaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__373->GetYaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__373->GetYaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__373->GetZaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__373->GetZaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__373->GetZaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__373->Draw("same PE");
   
   TH1D *hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__374 = new TH1D("hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__374","hRelYields_56_4",7,0,7);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__374->SetBinContent(5,0.3629264);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__374->SetBinError(5,0.002591761);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__374->SetEntries(1);

   ci = TColor::GetColor("#ff0000");
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__374->SetLineColor(ci);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__374->GetXaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__374->GetXaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__374->GetXaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__374->GetYaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__374->GetYaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__374->GetZaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__374->GetZaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__374->GetZaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__374->Draw("same PE");
   
   TH1D *hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__375 = new TH1D("hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__375","hRelYields_56_5",7,0,7);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__375->SetBinContent(6,0.07993319);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__375->SetBinError(6,0.0007326005);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__375->SetEntries(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__375->GetXaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__375->GetXaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__375->GetXaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__375->GetYaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__375->GetYaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__375->GetZaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__375->GetZaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__375->GetZaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__375->Draw("same PE");
   
   TH1D *hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__376 = new TH1D("hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__376","hRelYields_56_5",7,0,7);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__376->SetBinContent(6,0.3663039);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__376->SetBinError(6,0.004535783);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__376->SetEntries(1);

   ci = TColor::GetColor("#ff0000");
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__376->SetLineColor(ci);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__376->GetXaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__376->GetXaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__376->GetXaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__376->GetYaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__376->GetYaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__376->GetZaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__376->GetZaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__376->GetZaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__376->Draw("same PE");
   
   TH1D *hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__377 = new TH1D("hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__377","hRelYields_56_6",7,0,7);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__377->SetBinContent(7,0.07796704);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__377->SetBinError(7,0.001820971);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__377->SetEntries(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__377->GetXaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__377->GetXaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__377->GetXaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__377->GetYaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__377->GetYaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__377->GetZaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__377->GetZaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__377->GetZaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__377->Draw("same PE");
   
   TH1D *hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__378 = new TH1D("hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__378","hRelYields_56_6",7,0,7);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__378->SetBinContent(7,0.3522209);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__378->SetBinError(7,0.009296825);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__378->SetEntries(1);

   ci = TColor::GetColor("#ff0000");
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__378->SetLineColor(ci);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__378->GetXaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__378->GetXaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__378->GetXaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__378->GetYaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__378->GetYaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__378->GetZaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__378->GetZaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__378->GetZaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__378->Draw("same PE");
   
   TH1D *hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__379 = new TH1D("hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__379","hRelYields_84_0",7,0,7);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__379->SetBinContent(1,0.003900559);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__379->SetBinError(1,8.392592e-05);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__379->SetEntries(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__379->SetLineStyle(2);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__379->SetLineWidth(2);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__379->GetXaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__379->GetXaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__379->GetXaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__379->GetYaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__379->GetYaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__379->GetZaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__379->GetZaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__379->GetZaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__379->Draw("same PE");
   
   TH1D *hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__380 = new TH1D("hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__380","hRelYields_84_0",7,0,7);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__380->SetBinContent(1,0.09314935);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__380->SetBinError(1,0.001125983);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__380->SetEntries(1);

   ci = TColor::GetColor("#ff0000");
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__380->SetLineColor(ci);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__380->SetLineStyle(2);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__380->SetLineWidth(2);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__380->GetXaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__380->GetXaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__380->GetXaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__380->GetYaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__380->GetYaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__380->GetZaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__380->GetZaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__380->GetZaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__380->Draw("same PE");
   
   TH1D *hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__381 = new TH1D("hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__381","hRelYields_84_1",7,0,7);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__381->SetBinContent(2,0.004566185);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__381->SetBinError(2,9.538721e-05);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__381->SetEntries(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__381->SetLineStyle(2);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__381->SetLineWidth(2);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__381->GetXaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__381->GetXaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__381->GetXaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__381->GetYaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__381->GetYaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__381->GetZaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__381->GetZaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__381->GetZaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__381->Draw("same PE");
   
   TH1D *hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__382 = new TH1D("hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__382","hRelYields_84_1",7,0,7);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__382->SetBinContent(2,0.1938343);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__382->SetBinError(2,0.000992489);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__382->SetEntries(1);

   ci = TColor::GetColor("#ff0000");
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__382->SetLineColor(ci);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__382->SetLineStyle(2);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__382->SetLineWidth(2);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__382->GetXaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__382->GetXaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__382->GetXaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__382->GetYaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__382->GetYaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__382->GetZaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__382->GetZaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__382->GetZaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__382->Draw("same PE");
   
   TH1D *hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__383 = new TH1D("hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__383","hRelYields_84_2",7,0,7);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__383->SetBinContent(3,0.005470218);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__383->SetBinError(3,0.0001122489);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__383->SetEntries(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__383->SetLineStyle(2);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__383->SetLineWidth(2);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__383->GetXaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__383->GetXaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__383->GetXaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__383->GetYaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__383->GetYaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__383->GetZaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__383->GetZaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__383->GetZaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__383->Draw("same PE");
   
   TH1D *hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__384 = new TH1D("hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__384","hRelYields_84_2",7,0,7);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__384->SetBinContent(3,0.2454522);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__384->SetBinError(3,0.00136888);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__384->SetEntries(1);

   ci = TColor::GetColor("#ff0000");
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__384->SetLineColor(ci);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__384->SetLineStyle(2);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__384->SetLineWidth(2);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__384->GetXaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__384->GetXaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__384->GetXaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__384->GetYaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__384->GetYaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__384->GetZaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__384->GetZaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__384->GetZaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__384->Draw("same PE");
   
   TH1D *hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__385 = new TH1D("hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__385","hRelYields_84_3",7,0,7);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__385->SetBinContent(4,0.006422715);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__385->SetBinError(4,0.0001106851);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__385->SetEntries(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__385->SetLineStyle(2);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__385->SetLineWidth(2);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__385->GetXaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__385->GetXaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__385->GetXaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__385->GetYaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__385->GetYaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__385->GetZaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__385->GetZaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__385->GetZaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__385->Draw("same PE");
   
   TH1D *hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__386 = new TH1D("hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__386","hRelYields_84_3",7,0,7);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__386->SetBinContent(4,0.2820911);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__386->SetBinError(4,0.001895694);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__386->SetEntries(1);

   ci = TColor::GetColor("#ff0000");
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__386->SetLineColor(ci);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__386->SetLineStyle(2);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__386->SetLineWidth(2);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__386->GetXaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__386->GetXaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__386->GetXaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__386->GetYaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__386->GetYaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__386->GetZaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__386->GetZaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__386->GetZaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__386->Draw("same PE");
   
   TH1D *hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__387 = new TH1D("hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__387","hRelYields_84_4",7,0,7);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__387->SetBinContent(5,0.007221433);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__387->SetBinError(5,0.0001380513);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__387->SetEntries(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__387->SetLineStyle(2);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__387->SetLineWidth(2);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__387->GetXaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__387->GetXaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__387->GetXaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__387->GetYaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__387->GetYaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__387->GetZaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__387->GetZaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__387->GetZaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__387->Draw("same PE");
   
   TH1D *hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__388 = new TH1D("hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__388","hRelYields_84_4",7,0,7);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__388->SetBinContent(5,0.3012619);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__388->SetBinError(5,0.001826698);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__388->SetEntries(1);

   ci = TColor::GetColor("#ff0000");
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__388->SetLineColor(ci);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__388->SetLineStyle(2);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__388->SetLineWidth(2);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__388->GetXaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__388->GetXaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__388->GetXaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__388->GetYaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__388->GetYaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__388->GetZaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__388->GetZaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__388->GetZaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__388->Draw("same PE");
   
   TH1D *hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__389 = new TH1D("hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__389","hRelYields_84_5",7,0,7);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__389->SetBinContent(6,0.007526823);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__389->SetBinError(6,0.0002330599);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__389->SetEntries(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__389->SetLineStyle(2);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__389->SetLineWidth(2);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__389->GetXaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__389->GetXaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__389->GetXaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__389->GetYaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__389->GetYaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__389->GetZaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__389->GetZaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__389->GetZaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__389->Draw("same PE");
   
   TH1D *hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__390 = new TH1D("hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__390","hRelYields_84_5",7,0,7);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__390->SetBinContent(6,0.2967117);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__390->SetBinError(6,0.004211049);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__390->SetEntries(1);

   ci = TColor::GetColor("#ff0000");
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__390->SetLineColor(ci);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__390->SetLineStyle(2);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__390->SetLineWidth(2);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__390->GetXaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__390->GetXaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__390->GetXaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__390->GetYaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__390->GetYaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__390->GetZaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__390->GetZaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__390->GetZaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__390->Draw("same PE");
   
   TH1D *hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__391 = new TH1D("hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__391","hRelYields_84_6",7,0,7);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__391->SetBinContent(7,0.007174407);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__391->SetBinError(7,0.0004829804);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__391->SetEntries(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__391->SetLineStyle(2);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__391->SetLineWidth(2);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__391->GetXaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__391->GetXaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__391->GetXaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__391->GetYaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__391->GetYaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__391->GetZaxis()->SetLabelFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__391->GetZaxis()->SetTitleOffset(1);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__391->GetZaxis()->SetTitleFont(42);
   hRelYields_MONASH_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__391->Draw("same PE");
   
   TH1D *hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__392 = new TH1D("hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__392","hRelYields_84_6",7,0,7);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__392->SetBinContent(7,0.2794058);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__392->SetBinError(7,0.005839474);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__392->SetEntries(1);

   ci = TColor::GetColor("#ff0000");
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__392->SetLineColor(ci);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__392->SetLineStyle(2);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__392->SetLineWidth(2);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__392->GetXaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__392->GetXaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__392->GetXaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__392->GetYaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__392->GetYaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__392->GetZaxis()->SetLabelFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__392->GetZaxis()->SetTitleOffset(1);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__392->GetZaxis()->SetTitleFont(42);
   hRelYields_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__392->Draw("same PE");
   
   TPaveText *pt = new TPaveText(0.15,0.9308974,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("integrated yields for B^{+} trigger as function of multiplicity");
   pt->Draw();
   mainPadRelJunctions_integrated->Modified();
   cRelYields_integrated yields for B^{+} trigger as function of multiplicity->cd();
  
// ------------>Primitives in pad: miniPadRelJunctions_integrated yields for B^{+} trigger as function of multiplicity
   TPad *miniPadRelJunctions_integrated = new TPad("miniPadRelJunctions_integrated yields for B^{+} trigger as function of multiplicity", "miniPad",0.05,0.1,0.95,0.3);
   miniPadRelJunctions_integrated->Draw();
   miniPadRelJunctions_integrated->cd();
   miniPadRelJunctions_integrated->Range(-0.8750001,-1.557029,7.875,1.903036);
   miniPadRelJunctions_integrated->SetFillColor(0);
   miniPadRelJunctions_integrated->SetBorderMode(0);
   miniPadRelJunctions_integrated->SetBorderSize(2);
   miniPadRelJunctions_integrated->SetLogy();
   miniPadRelJunctions_integrated->SetTopMargin(0);
   miniPadRelJunctions_integrated->SetBottomMargin(0.45);
   miniPadRelJunctions_integrated->SetFrameBorderMode(0);
   miniPadRelJunctions_integrated->SetFrameBorderMode(0);
   
   TH1D *hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393 = new TH1D("hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393","",7,0,7);
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->SetMinimum(1);
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->SetMaximum(79.99);
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->SetStats(0);

   ci = TColor::GetColor("#000099");
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->SetLineColor(ci);
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetXaxis()->SetBinLabel(1,"  80-100 % multiplicity bin");
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetXaxis()->SetBinLabel(2,"  60-80 % multiplicity bin");
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetXaxis()->SetBinLabel(3,"  40-60 % multiplicity bin");
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetXaxis()->SetBinLabel(4,"  20-40 % multiplicity bin");
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetXaxis()->SetBinLabel(5,"  5-20 % multiplicity bin");
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetXaxis()->SetBinLabel(6,"  1-5% multiplicity bin");
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetXaxis()->SetBinLabel(7,"  top 1% multiplicity bin");
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetXaxis()->SetLabelFont(42);
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetXaxis()->SetLabelOffset(0.035);
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetXaxis()->SetLabelSize(0.15);
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetXaxis()->SetTitleSize(0.105);
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetXaxis()->SetTickLength(0.105);
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetXaxis()->SetTitleOffset(1.75);
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetXaxis()->SetTitleFont(42);
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetYaxis()->SetTitle("JUN / MON");
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetYaxis()->SetLabelFont(42);
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetYaxis()->SetLabelSize(0.105);
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetYaxis()->SetTitleSize(0.105);
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetYaxis()->SetTitleOffset(0.42);
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetYaxis()->SetTitleFont(42);
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetZaxis()->SetLabelFont(42);
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetZaxis()->SetTitleOffset(1);
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->GetZaxis()->SetTitleFont(42);
   hRelYieldsRatioTemplate_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity__393->Draw("PE");
   
   TH1D *hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__394 = new TH1D("hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__394","hRelYieldsRatio_56_0",7,0,7);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__394->SetBinContent(1,1.818664);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__394->SetBinError(1,0.01751675);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__394->SetEntries(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__394->GetXaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__394->GetXaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__394->GetXaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__394->GetYaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__394->GetYaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__394->GetZaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__394->GetZaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__394->GetZaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_0__394->Draw("same PE");
   
   TH1D *hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__395 = new TH1D("hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__395","hRelYieldsRatio_56_1",7,0,7);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__395->SetBinContent(2,3.039729);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__395->SetBinError(2,0.02053769);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__395->SetEntries(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__395->GetXaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__395->GetXaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__395->GetXaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__395->GetYaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__395->GetYaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__395->GetZaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__395->GetZaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__395->GetZaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_1__395->Draw("same PE");
   
   TH1D *hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__396 = new TH1D("hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__396","hRelYieldsRatio_56_2",7,0,7);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__396->SetBinContent(3,3.752922);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__396->SetBinError(3,0.0379603);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__396->SetEntries(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__396->GetXaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__396->GetXaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__396->GetXaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__396->GetYaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__396->GetYaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__396->GetZaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__396->GetZaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__396->GetZaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_2__396->Draw("same PE");
   
   TH1D *hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__397 = new TH1D("hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__397","hRelYieldsRatio_56_3",7,0,7);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__397->SetBinContent(4,4.253522);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__397->SetBinError(4,0.02433574);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__397->SetEntries(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__397->GetXaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__397->GetXaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__397->GetXaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__397->GetYaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__397->GetYaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__397->GetZaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__397->GetZaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__397->GetZaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_3__397->Draw("same PE");
   
   TH1D *hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__398 = new TH1D("hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__398","hRelYieldsRatio_56_4",7,0,7);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__398->SetBinContent(5,4.539787);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__398->SetBinError(5,0.045988);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__398->SetEntries(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__398->GetXaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__398->GetXaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__398->GetXaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__398->GetYaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__398->GetYaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__398->GetZaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__398->GetZaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__398->GetZaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_4__398->Draw("same PE");
   
   TH1D *hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__399 = new TH1D("hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__399","hRelYieldsRatio_56_5",7,0,7);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__399->SetBinContent(6,4.582625);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__399->SetBinError(6,0.07420004);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__399->SetEntries(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__399->GetXaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__399->GetXaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__399->GetXaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__399->GetYaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__399->GetYaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__399->GetZaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__399->GetZaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__399->GetZaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_5__399->Draw("same PE");
   
   TH1D *hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__400 = new TH1D("hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__400","hRelYieldsRatio_56_6",7,0,7);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__400->SetBinContent(7,4.517562);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__400->SetBinError(7,0.1732796);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__400->SetEntries(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__400->GetXaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__400->GetXaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__400->GetXaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__400->GetYaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__400->GetYaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__400->GetZaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__400->GetZaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__400->GetZaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_56_6__400->Draw("same PE");
   
   TH1D *hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__401 = new TH1D("hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__401","hRelYieldsRatio_84_0",7,0,7);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__401->SetBinContent(1,23.88103);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__401->SetBinError(1,0.6723317);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__401->SetEntries(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__401->SetLineStyle(2);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__401->SetLineWidth(2);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__401->GetXaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__401->GetXaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__401->GetXaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__401->GetYaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__401->GetYaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__401->GetZaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__401->GetZaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__401->GetZaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_0__401->Draw("same PE");
   
   TH1D *hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__402 = new TH1D("hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__402","hRelYieldsRatio_84_1",7,0,7);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__402->SetBinContent(2,42.44994);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__402->SetBinError(2,0.8706202);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__402->SetEntries(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__402->SetLineStyle(2);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__402->SetLineWidth(2);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__402->GetXaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__402->GetXaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__402->GetXaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__402->GetYaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__402->GetYaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__402->GetZaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__402->GetZaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__402->GetZaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_1__402->Draw("same PE");
   
   TH1D *hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__403 = new TH1D("hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__403","hRelYieldsRatio_84_2",7,0,7);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__403->SetBinContent(3,44.87065);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__403->SetBinError(3,0.8908855);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__403->SetEntries(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__403->SetLineStyle(2);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__403->SetLineWidth(2);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__403->GetXaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__403->GetXaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__403->GetXaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__403->GetYaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__403->GetYaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__403->GetZaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__403->GetZaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__403->GetZaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_2__403->Draw("same PE");
   
   TH1D *hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__404 = new TH1D("hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__404","hRelYieldsRatio_84_3",7,0,7);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__404->SetBinContent(4,43.92084);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__404->SetBinError(4,0.7946022);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__404->SetEntries(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__404->SetLineStyle(2);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__404->SetLineWidth(2);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__404->GetXaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__404->GetXaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__404->GetXaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__404->GetYaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__404->GetYaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__404->GetZaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__404->GetZaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__404->GetZaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_3__404->Draw("same PE");
   
   TH1D *hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__405 = new TH1D("hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__405","hRelYieldsRatio_84_4",7,0,7);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__405->SetBinContent(5,41.71774);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__405->SetBinError(5,0.9194067);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__405->SetEntries(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__405->SetLineStyle(2);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__405->SetLineWidth(2);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__405->GetXaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__405->GetXaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__405->GetXaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__405->GetYaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__405->GetYaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__405->GetZaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__405->GetZaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__405->GetZaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_4__405->Draw("same PE");
   
   TH1D *hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__406 = new TH1D("hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__406","hRelYieldsRatio_84_5",7,0,7);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__406->SetBinContent(6,39.42058);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__406->SetBinError(6,1.455157);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__406->SetEntries(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__406->SetLineStyle(2);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__406->SetLineWidth(2);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__406->GetXaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__406->GetXaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__406->GetXaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__406->GetYaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__406->GetYaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__406->GetZaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__406->GetZaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__406->GetZaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_5__406->Draw("same PE");
   
   TH1D *hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__407 = new TH1D("hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__407","hRelYieldsRatio_84_6",7,0,7);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__407->SetBinContent(7,38.94479);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__407->SetBinError(7,2.923969);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__407->SetEntries(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__407->SetLineStyle(2);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__407->SetLineWidth(2);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__407->GetXaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__407->GetXaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__407->GetXaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__407->GetYaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__407->GetYaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__407->GetZaxis()->SetLabelFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__407->GetZaxis()->SetTitleOffset(1);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__407->GetZaxis()->SetTitleFont(42);
   hRelYieldsRatio_JUNCTIONS_integratedsPyieldssPforsPBhA{pL}sPtriggersPassPfunctionsPofsPmultiplicity_84_6__407->Draw("same PE");
   miniPadRelJunctions_integrated->Modified();
   cRelYields_integrated yields for B^{+} trigger as function of multiplicity->cd();
   cRelYields_integrated->Modified();
   cRelYields_integrated yields for B^{+} trigger as function of multiplicity->cd();
   cRelYields_integrated yields for B^{+} trigger as function of multiplicity->SetSelected(cRelYields_integrated yields for B^{+} trigger as function of multiplicity);
}
